<?php $_product = $this->getProduct(); ?>
<?php $buttonTitle = $this->__('Add to Cart'); ?>
<?php if($_product->isSaleable()): ?>
    <div class="add-to-cart">
        <?php if(!$_product->isGrouped()): ?>

        <label for="qty"><?php echo $this->__('Qty:') ?></label>
        <input type="text"  name="qty" id="qty" keypress="" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
        <?php endif; ?>
        <button type="button" title="<?php echo $buttonTitle ?>" class="button btn-cart" onclick="productAddToCartForm.submit(this)"><span><span><?php echo $buttonTitle ?></span></span></button>
        <span id='ajax_loader' style='display:none'><img src='<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif')?>'/></span>        
        <?php echo $this->getChildHtml('', true, true) ?>
    </div>
<?php endif; ?>
<script type="text/javascript">
  
   jQuery("#qty").keypress(function(e) {
       
   if(e.which==13)
       {   
             var obj = document.getElementById("qty");
              if(parseInt(obj.value)<1)
            {
                alert("Please specify Quantity");
            }
            else
                {
           jQuery('.btn-cart').trigger('click');
                }
            return false;
       }
});      


    </script>

